---

- hosts: all
  become: true
  tasks:

  - name: Install Apache Package and PHP Support for Apache
    package:
      name: apache2
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
