---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update_cache: yes

  - name: Desinstall apache2 package
    apt:
      name: apache2
      state: absent

  - name: Delete PHP Support for Apache
    apt:
      name: libapache2-mod-php
      state: absent
