---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates on CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install Updates on Ubunt
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache Package and PHP Support for Ubuntu Servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache and PHP for CentOs Servers
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Copy Default HTML file for Site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/hrml/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB Package in CentOS
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install MariaDB Package in Ubuntu
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Install Samba Package
    tags: samba
    package:
      name: samba
      state: latest
